// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// resample_poly_cpp
NumericVector resample_poly_cpp(NumericVector x, NumericVector h, int up);
RcppExport SEXP _mrpheus_resample_poly_cpp(SEXP xSEXP, SEXP hSEXP, SEXP upSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type up(upSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_poly_cpp(x, h, up));
    return rcpp_result_gen;
END_RCPP
}
// perm_entropy_cpp
double perm_entropy_cpp(NumericVector x, int order, int delay);
RcppExport SEXP _mrpheus_perm_entropy_cpp(SEXP xSEXP, SEXP orderSEXP, SEXP delaySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type delay(delaySEXP);
    rcpp_result_gen = Rcpp::wrap(perm_entropy_cpp(x, order, delay));
    return rcpp_result_gen;
END_RCPP
}
// higuchi_fd_cpp
double higuchi_fd_cpp(NumericVector x, int kmax);
RcppExport SEXP _mrpheus_higuchi_fd_cpp(SEXP xSEXP, SEXP kmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type kmax(kmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(higuchi_fd_cpp(x, kmax));
    return rcpp_result_gen;
END_RCPP
}
// roll_triang_mean_cpp
NumericVector roll_triang_mean_cpp(NumericVector x, int k);
RcppExport SEXP _mrpheus_roll_triang_mean_cpp(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(roll_triang_mean_cpp(x, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mrpheus_resample_poly_cpp", (DL_FUNC) &_mrpheus_resample_poly_cpp, 3},
    {"_mrpheus_perm_entropy_cpp", (DL_FUNC) &_mrpheus_perm_entropy_cpp, 3},
    {"_mrpheus_higuchi_fd_cpp", (DL_FUNC) &_mrpheus_higuchi_fd_cpp, 2},
    {"_mrpheus_roll_triang_mean_cpp", (DL_FUNC) &_mrpheus_roll_triang_mean_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mrpheus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
