# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resample_poly_cpp <- function(x, h, up) {
    .Call(`_mrpheus_resample_poly_cpp`, x, h, up)
}

perm_entropy_cpp <- function(x, order = 3L, delay = 1L) {
    .Call(`_mrpheus_perm_entropy_cpp`, x, order, delay)
}

higuchi_fd_cpp <- function(x, kmax = 10L) {
    .Call(`_mrpheus_higuchi_fd_cpp`, x, kmax)
}

roll_triang_mean_cpp <- function(x, k = 15L) {
    .Call(`_mrpheus_roll_triang_mean_cpp`, x, k)
}

