# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roll_rms_cpp <- function(x, k) {
    .Call(`_mrpheus_roll_rms_cpp`, x, k)
}

detect_so_candidates_cpp <- function(sig, sr, dur_neg_min, dur_neg_max, dur_pos_min, dur_pos_max, amp_min, amp_max) {
    .Call(`_mrpheus_detect_so_candidates_cpp`, sig, sr, dur_neg_min, dur_neg_max, dur_pos_min, dur_pos_max, amp_min, amp_max)
}

resample_poly_cpp <- function(x, h, up) {
    .Call(`_mrpheus_resample_poly_cpp`, x, h, up)
}

perm_entropy_cpp <- function(x, order = 3L, delay = 1L) {
    .Call(`_mrpheus_perm_entropy_cpp`, x, order, delay)
}

higuchi_fd_cpp <- function(x, kmax = 10L) {
    .Call(`_mrpheus_higuchi_fd_cpp`, x, kmax)
}

roll_triang_mean_cpp <- function(x, k = 15L) {
    .Call(`_mrpheus_roll_triang_mean_cpp`, x, k)
}

nzc_cpp <- function(x) {
    .Call(`_mrpheus_nzc_cpp`, x)
}

petrosian_fd_cpp <- function(x) {
    .Call(`_mrpheus_petrosian_fd_cpp`, x)
}

hjorth_cpp <- function(x) {
    .Call(`_mrpheus_hjorth_cpp`, x)
}

stat_features_cpp <- function(x) {
    .Call(`_mrpheus_stat_features_cpp`, x)
}

rowmedian_cpp <- function(x) {
    .Call(`_mrpheus_rowmedian_cpp`, x)
}

roll_right_mean_cpp <- function(x, k = 4L) {
    .Call(`_mrpheus_roll_right_mean_cpp`, x, k)
}

robust_scale_cpp <- function(x, q_low = 0.05, q_high = 0.95) {
    .Call(`_mrpheus_robust_scale_cpp`, x, q_low, q_high)
}

